spring:
    kafka:
        bootstrap-servers: kafka:9092
    cloud:
        stream:
            bindings:
                adverbfunction-in-0:
                    destination: adverbrequest
                adverbfunction-out-0:
                    destination: adverbresponse
